package wrtmpl

const (
	tmplProtoFileCommentText = `// Protocol generated by excelconfc. DO NOT EDIT.
// source:
//   file: {{.SourceFile}}
//   sheet: {{.SourceSheet}}
`
	tmplProtoDeclText = `
syntax = "proto3";

package {{.PackageName}};

option go_package = "{{.GoPackage}}";
`
)
