// Code generated by excelconfc. DO NOT EDIT.
// source:
//   file: ExcelConfTest.xlsx
//   sheet: ActTaskConf

package excelconf

import (
	"encoding/json"
	"encoding/xml"
	"os"
)

type AwardItem struct {
	ItemId uint32 `json:"item_id,omitempty" xml:"item_id"`
	Num    uint32 `json:"num,omitempty" xml:"num"`
}

type ActTaskConf struct {
	TaskId     uint32      `json:"task_id,omitempty" xml:"task_id"`
	Title      string      `json:"title,omitempty" xml:"title"`
	TargetId   uint32      `json:"target_id,omitempty" xml:"target_id"`
	TargetType uint32      `json:"target_type,omitempty" xml:"target_type"`
	Progress   uint32      `json:"progress,omitempty" xml:"progress"`
	Awards     []AwardItem `json:"awards,omitempty" xml:"awards>item"`
}

type ActTaskConfMap map[uint32]*ActTaskConf

func (s ActTaskConfMap) LoadFromJsonFile(filePath string) error {
	fileBytes, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	jsonData := struct {
		Data []*ActTaskConf `json:"data"`
	}{}
	if err := json.Unmarshal(fileBytes, &jsonData); err != nil {
		return err
	}
	for _, conf := range jsonData.Data {
		s[conf.TaskId] = conf
	}
	return nil
}

func (s ActTaskConfMap) LoadFromXmlFile(filePath string) error {
	fileBytes, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	xmlData := struct {
		Data []*ActTaskConf `xml:"all_infos>item"`
	}{}
	if err := xml.Unmarshal(fileBytes, &xmlData); err != nil {
		return err
	}
	for _, conf := range xmlData.Data {
		s[conf.TaskId] = conf
	}
	return nil
}

func (s ActTaskConfMap) GetVal(key uint32) *ActTaskConf {
	return s[key]
}

var instanceActTaskConfMap = make(ActTaskConfMap)

func GetActTaskConfMapInst() ActTaskConfMap {
	return instanceActTaskConfMap
}
