// Code generated by excelconfc. DO NOT EDIT.
// source:
//   file: ExcelConfTest.xlsx
//   sheet: GroupFlagTestConf

package excelconf

import (
	"encoding/json"
	"os"
)

type TaskRef struct {
	TaskId int32 `json:"task_id,omitempty"`
}

type ClientTaskResource struct {
	TaskId    int32  `json:"task_id,omitempty"`
	NewTaskId int32  `json:"new_task_id,omitempty"`
	Desc      string `json:"desc,omitempty"`
}

type GroupFlagTestConf struct {
	Id            int32              `json:"id,omitempty"`
	TaskRefVec    []TaskRef          `json:"task_ref_vec,omitempty"`
	HotUpdateItem ClientTaskResource `json:"hot_update_item,omitempty"`
	ActId         int64              `json:"act_id,omitempty"`
}

type GroupFlagTestConfMap map[int32]*GroupFlagTestConf

func (s GroupFlagTestConfMap) LoadFromJsonFile(filePath string) error {
	fileBytes, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	jsonData := struct {
		Data []GroupFlagTestConf `json:"data"`
	}{}
	json.Unmarshal(fileBytes, &jsonData)
	for _, conf := range jsonData.Data {
		s[conf.Id] = &conf
	}
	return nil
}

func (s GroupFlagTestConfMap) GetVal(key int32) *GroupFlagTestConf {
	return s[key]
}

var instanceGroupFlagTestConfMap = make(GroupFlagTestConfMap)

func GetGroupFlagTestConfMapInst() GroupFlagTestConfMap {
	return instanceGroupFlagTestConfMap
}
