// Code generated by excelconfc. DO NOT EDIT.
// source:
//   file: ExcelConfTest.xlsx
//   sheet: NestFieldsTestConf

package excelconf

import (
	"encoding/json"
	"os"
)

type TypeAA struct {
	Aa1 int32  `json:"aa1,omitempty"`
	Aa2 string `json:"aa2,omitempty"`
}

type TypeA struct {
	A1 int32    `json:"a1,omitempty"`
	A2 int32    `json:"a2,omitempty"`
	AA []TypeAA `json:"AA,omitempty"`
	A3 string   `json:"a3,omitempty"`
}

type TypeB struct {
	B1 int32  `json:"b1,omitempty"`
	B2 int32  `json:"b2,omitempty"`
	B3 string `json:"b3,omitempty"`
}

type NestFieldsTestConf struct {
	Id int32   `json:"id,omitempty"`
	A  []TypeA `json:"A,omitempty"`
	B  TypeB   `json:"B,omitempty"`
	C  int64   `json:"C,omitempty"`
}

type NestFieldsTestConfMap map[int32]*NestFieldsTestConf

func (s NestFieldsTestConfMap) LoadFromJsonFile(filePath string) error {
	fileBytes, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	jsonData := struct {
		Data []NestFieldsTestConf `json:"data"`
	}{}
	json.Unmarshal(fileBytes, &jsonData)
	for _, conf := range jsonData.Data {
		s[conf.Id] = &conf
	}
	return nil
}

func (s NestFieldsTestConfMap) GetVal(key int32) *NestFieldsTestConf {
	return s[key]
}

var instanceNestFieldsTestConfMap = make(NestFieldsTestConfMap)

func GetNestFieldsTestConfMapInst() NestFieldsTestConfMap {
	return instanceNestFieldsTestConfMap
}
